In [ ]:
#1.Write a Python program that takes two numbers as input and divides them.
#Handle the case when the user enters zero as the denominator.
try:
  a=int(input("enter first number :"))
  b=int(input("enter second number :"))
  c=a/b


except:
  print("divide by non zero otherwise uh will get infite number")
else:
  print(a)
  print(b)
  print(c)

print("this is last line")

enter first number2
enter second number0
divide by non zero otherwise uh will get infite number
this is last line

In [ ]:
#2.Write a program to open a file named "data.txt" and print its content.
#If the file does not exist, handle the exception and print "File not found!".

In [ ]:
#3.Create a program that asks for a number and prints its square.
#Handle cases when the user enters text or special characters instead of a number.
try:
  number=int(input("Enter a number :"))
  square=number**2

except:
  print("Please enter a valid number")
else:
  print("The square of number is: ",square)

Enter a number :@
Please enter a valid number

In [ ]:
# 4.Write a program that handles multiple exceptions — ValueError and
# ZeroDivisionError — when dividing two user inputs.
try:
  num1=int(input("Enter a number one :"))
  num2=int(input("Enter a number two :"))
  c=num1/num2
except ValueError:
  print("Invalid input")
except ZeroDivisionError:
  print("Cannot divide by zero")
else:
  print("Division Sucessful :",c)

Enter a number one :2
Enter a number two :0
Cannot divide by zero

In [ ]:
#5.Write a program using try-except-finally where:You take input for a number, divide it by 5,Print the result,And always print "Program finished" in the finally block.
try:
  num=int(input("Enter a number :"))
  c=num/5
except:
  print("Enter a valid number")
else:
  print(c)
finally:
  print("Program finished")

Enter a number :10
2.0
Program finished

In [ ]:
#6.Create a Pandas Series from a dictionary of 5 items (keys as country names, values as populations).Print all index labels, data values, and data type.
#Then convert the Series to a Python dictionary using .to_dict().

In [ ]:
#7.Create a Series from a tuple (100, 200, 300, 400, 500).Display the 2nd to 4th elements using slicing. Display only the even-indexed elements.
t=(100,200,300,400,500)
data=pd.Series(t)
data.iloc[2:5:2]

2    300
4    500
dtype: int64

In [ ]:
#8.Create a Series from [5, 10, 15, 20, 25, 30].Display its size, dimension, index type, and value type.Then convert it to a NumPy array using .to_numpy().
import numpy as np

data=[5,10,15,20,25,30]
s=pd.Series(data)

print(s.size)
print(s.ndim)
print(s.index)
print(s.dtype)
numpy_array=s.to_numpy()
print(numpy_array)

6
1
RangeIndex(start=0, stop=6, step=1)
int64
[ 5 10 15 20 25 30]

In [ ]:
#9.Create a Series from a dictionary of student names and marks.Print the top 2 marks using .nlargest(2) and bottom 2 marks using .nsmallest(2).
import pandas as pd
data={
    "Affan":98,
    "Tanmay":88,
    "Vijay":45,
    "Rohit":12,
    "Viraj":65
}
s=pd.Series(data)
print(s.nlargest(2))
print(s.nsmallest(2))

Affan     98
Tanmay    88
dtype: int64
Rohit    12
Vijay    45
dtype: int64

In [ ]:
#10.Create a Series with numeric values and some NAN values.Use .isnull(), .notnull(), .count(), and .sum() to analyze missing data.
import numpy as np
data=[1,2,3,4,5,np.nan,6,7,8,np.nan]
s=pd.Series(data)
print(s.isnull())
print(s.notnull())
print(s.count())

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
8    False
9     True
dtype: bool
0     True
1     True
2     True
3     True
4     True
5    False
6     True
7     True
8     True
9    False
dtype: bool
8

In [ ]:
#11.Create a DataFrame using a nested dictionary:
data = {
    'Student1': {'Math': 80, 'Science': 85},
    'Student2': {'Math': 75, 'Science': 90},
    'Student3': {'Math': 88, 'Science': 82}
}
df = pd.DataFrame(data)
print(df)

         Student1  Student2  Student3
Math           80        75        88
Science        85        90        82

In [ ]:
# 12.Create a DataFrame with this data:Display only the "Name" and "City" columns using column selection.Then use .loc to show data for index 1 only.
Name = ['Amit', 'Riya', 'Sam']
Age = [22, 23, 21]
City = ['Pune', 'Delhi', 'Mumbai']
data = {'Name': Name, 'Age': Age, 'City': City}
df = pd.DataFrame(data)
df[['Name','City']]
df.iloc[1]

Name     Riya
Age        23
City    Delhi
Name: 1, dtype: object

In [ ]:
#13.Create a DataFrame with 3 rows and 3 columns of your choice.Change the index names to ['One', 'Two', 'Three'].Change the column names using .rename().
import pandas as pd

# Create a DataFrame with 3 rows and 3 columns of your choice
data = {
    'ColA': [10, 20, 30],
    'ColB': [100, 200, 300],
    'ColC': [1000, 2000, 3000]
}
df = pd.DataFrame(data)
df
df.index=['one','Two','Three']
df
df.rename(columns={'ColA':'A','ColB':'B','ColC':'C'})

        A    B     C
one    10  100  1000
Two    20  200  2000
Three  30  300  3000

In [ ]:
#14.Create a DataFrame and use: df.head(2),df.tail(2),df.describe(),df.info()
import pandas as pd
data={
    'Name':['Affan','Vijay','Tanmay'],
    'Age':[20,21,22]
}
df=pd.DataFrame(data)
df
print(df.head(2))
print(df.tail(2))
print(df.describe())
print(df.info())

    Name  Age
0  Affan   20
1  Vijay   21
     Name  Age
1   Vijay   21
2  Tanmay   22
        Age
count   3.0
mean   21.0
std     1.0
min    20.0
25%    20.5
50%    21.0
75%    21.5
max    22.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes
None

In [ ]:
#15.Create a DataFrame of 5 students with marks in two subjects.Find the mean marks for each subject using .mean().
#Find the maximum and minimum marks using .max() and .min().

import pandas as pd
data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Math': [85, 90, 78, 92, 88],
    'Science': [70, 85, 91, 75, 80]
}
df= pd.DataFrame(data)
df

mean_marks = df[['Math', 'Science']].mean()
print(mean_marks)

max_marks = df[['Math', 'Science']].max()
print(max_marks)

min_marks = df[['Math', 'Science']].min()
print(min_marks)

Math       86.6
Science    80.2
dtype: float64
Math       92
Science    91
dtype: int64
Math       78
Science    70
dtype: int64